site_name: Neko-Guide
theme:
    name: material
    font:
        text: Noto Sans
        code: Jetbrains Mono
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
