[project]
name = "guide-nekoray"
version = "0.0.1"
description = "Simple doc for nekoray"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.11",
]
